Laravel 8
rinvex/laravel-support pull request #38
Opened 2020-09-10 08:08 UTC by sashsvamir

2020-11-16 12:03 UTC, abdrzakoxa requested changes

2020-11-16 12:03 UTC, abdrzakoxa commented on composer.json
> +        "illuminate/validation": "^8.0.0",
add ^7.0.0|^8.0.0 to support laravel 7 and 8

2020-12-02 07:38 UTC, r8928 commented
please update

2020-12-25 03:39 UTC, Omranic commented
Hello, thank you for your patience, this is now done! Check latest major release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @sashsvamir @abdrzakoxa @r8928

2020-12-25 03:39 UTC, closed without merging